
server:
  port: 8080

spring:
  datasource:
    username: root
    password: mySQLuser@@5
    url: jdbc:mysql://localhost:3306/new_schema
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    format_sql: true

servlet:
  multipart:
    max-file-size: 5MB
    max-request-size: 5MB
    file-size-threshold: 2KB
